apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: NEO4J_LOCAL_URI
              value: bolt://neo4j:7687
            - name: OLLAMA_HOST
              value: http://ollama-service:11434
            - name: BACKEND_HOST
              value: "localhost"
          imagePullPolicy: IfNotPresent
          name: orchestrator
          image: trip-app:latest
          resources:
            limits:
              memory: "1Gi"
              cpu: "2"
            requests:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 8001
          volumeMounts:
            - mountPath: /app/user_img
              name: shared-images
        - env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: HF_HOME
              value: /root/.cache/huggingface
            - name: NEO4J_LOCAL_URI
              value: bolt://neo4j:7687
            - name: OLLAMA_HOST
              value: http://ollama-service:11434
          image: trip-backend:latest
          imagePullPolicy: IfNotPresent
          name: backend
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              memory: "6Gi"
              cpu: "4"
              # nvidia.com/gpu: 1
            requests:
              memory: "2Gi"
              cpu: "1"
              # nvidia.com/gpu: 1
          volumeMounts:
            - mountPath: /root/.cache/huggingface
              name: backend-claim1
            - mountPath: /app/user_img
              name: shared-images
      volumes:
        - name: backend-claim1
          persistentVolumeClaim:
            claimName: backend-claim1
        # - name: backend-claim1
        #   hostPath:
        #     path: /run/desktop/mnt/host/d/trip_model_repo/huggingface
        #     type: DirectoryOrCreate
        - name: shared-images
          emptyDir: {}