apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: base
  name: base
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: base
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: base
    spec:
      containers:
        - image: myproject/base:latest
          name: base
      restartPolicy: Always
