apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: neo4j
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: neo4j
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: neo4j
    spec:
      containers:
        - env:
            - name: NEO4J_AUTH
              value: neo4j/neo4j_pw
            - name: NEO4J_PLUGINS
              value: '["apoc"]'
            - name: NEO4J_dbms_security_procedures_allowlist
              value: apoc.*
            - name: NEO4J_dbms_security_procedures_unrestricted
              value: apoc.*
            - name: NEO4J_server_config_strict__validation_enabled
              value: "false"
            - name: NEO4J_server_memory_heap_max__size
              value: 2G #1G
            - name: NEO4J_server_memory_pagecache_size
              value: 1G #512M
          resources:
            limits:
              memory: "6Gi"
              cpu: "1"
            requests:
              memory: "4Gi"
              cpu: "500m"
          image: neo4j:5-community
          name: neo4j
          ports:
            - containerPort: 7474
              protocol: TCP
            - containerPort: 7687
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: neo4j-data
      restartPolicy: Always
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-data
      # volumes:
      # - name: neo4j-data
      #   hostPath:
      #     path: /neo4j-bridge
      #     type: Directory